name: Azure Static Web App Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js version
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'  # Specify Node.js version here

    - name: Build app
      run: |
        yarn
        yarn build
        
    - name: Deploy WebApp to Static Web App
      uses: Azure/static-web-apps-deploy@v2
      with:
        azure_static_web_apps_api_token: ${{ secrets.MANAGE_DEPLOYMENT_TOKEN }}
        action: 'upload'
        app_location: '/'
        api_location: 'api'
        output_location: './dist'
