name: deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js version
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install apt-utils
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-utils  

    - name: build app
      run: |
        yarn
        yarn build
    - name: Deploy WebApp to Static Web App
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.MANAGE_DEPLOYMENT_TOKEN }}
         # Used for GitHub integrations (i.e. PR comments)
        action: 'upload'
        #app_location: 'auth-app'
        #api_location: ''
        output_location: './dist'
      env:
       MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
