name: deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js version
      uses: actions/setup-node@v2
      with:
        node-version: '18' 

    - name: build app
      run: |
        npm cache clean --force         #*try clearing out npm cache*
        npm install --legacy-peer-deps  #*run the command with the --legacy-peer-deps option*
        #npm install --force             #* run the command with the --force*
        npm run build
        npm run dev      
    - name: Deploy WebApp to Static Web App
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.MANAGE_DEPLOYMENT_TOKEN }}
        action: 'upload'
        #app_location: 'auth-app'
        #api_location: ''
        output_location: './dist'
